# Generated by Django 2.1.3 on 2018-12-02 17:29

import battleships.models.ship
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='experience',
            field=models.CharField(default=battleships.models.ship.Experience('RECRUIT'), max_length=20),
        ),
        migrations.AlterField(
            model_name='destroyer',
            name='experience',
            field=models.CharField(default=battleships.models.ship.Experience('RECRUIT'), max_length=20),
        ),
        migrations.AlterField(
            model_name='frigate',
            name='experience',
            field=models.CharField(default=battleships.models.ship.Experience('RECRUIT'), max_length=20),
        ),
        migrations.AlterField(
            model_name='submarine',
            name='experience',
            field=models.CharField(default=battleships.models.ship.Experience('RECRUIT'), max_length=20),
        ),
    ]
