# Generated by Django 2.1.3 on 2018-12-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0004_auto_20181202_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='ship1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='battleships.Carrier'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='ship2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='battleships.Destroyer'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='ship3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='battleships.Frigate'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='ship4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='battleships.Submarine'),
        ),
    ]
