# Generated by Django 2.1.3 on 2018-12-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0005_auto_20181202_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='ship1',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='coordinate',
            old_name='ship2',
            new_name='destroyer',
        ),
        migrations.RenameField(
            model_name='coordinate',
            old_name='ship3',
            new_name='frigate',
        ),
        migrations.RenameField(
            model_name='coordinate',
            old_name='ship4',
            new_name='submarine',
        ),
    ]
