# Generated by Django 2.1.3 on 2018-12-17 23:38

import battleships.models.ship
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0006_auto_20181202_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='experience',
            field=models.CharField(choices=[battleships.models.ship.Experience('RECRUIT'), battleships.models.ship.Experience('SOLDIER'), battleships.models.ship.Experience('VETERAN')], default=battleships.models.ship.Experience('RECRUIT'), max_length=20),
        ),
        migrations.AlterField(
            model_name='destroyer',
            name='experience',
            field=models.CharField(choices=[battleships.models.ship.Experience('RECRUIT'), battleships.models.ship.Experience('SOLDIER'), battleships.models.ship.Experience('VETERAN')], default=battleships.models.ship.Experience('RECRUIT'), max_length=20),
        ),
        migrations.AlterField(
            model_name='frigate',
            name='experience',
            field=models.CharField(choices=[battleships.models.ship.Experience('RECRUIT'), battleships.models.ship.Experience('SOLDIER'), battleships.models.ship.Experience('VETERAN')], default=battleships.models.ship.Experience('RECRUIT'), max_length=20),
        ),
        migrations.AlterField(
            model_name='submarine',
            name='experience',
            field=models.CharField(choices=[battleships.models.ship.Experience('RECRUIT'), battleships.models.ship.Experience('SOLDIER'), battleships.models.ship.Experience('VETERAN')], default=battleships.models.ship.Experience('RECRUIT'), max_length=20),
        ),
    ]
