# Generated by Django 2.1.3 on 2019-01-15 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0013_auto_20190111_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
