# Generated by Django 2.1.3 on 2018-12-02 17:10

import battleships.models.ship
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('strength', models.IntegerField(default=0)),
                ('experience', models.CharField(default=battleships.models.ship.Experience('RECRUIT'), max_length=7)),
                ('experience_points', models.IntegerField(default=0)),
                ('visibility_radius', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name=0)),
                ('y', models.IntegerField(verbose_name=0)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Destroyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('strength', models.IntegerField(default=0)),
                ('experience', models.CharField(default=battleships.models.ship.Experience('RECRUIT'), max_length=7)),
                ('experience_points', models.IntegerField(default=0)),
                ('visibility_radius', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frigate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('strength', models.IntegerField(default=0)),
                ('experience', models.CharField(default=battleships.models.ship.Experience('RECRUIT'), max_length=7)),
                ('experience_points', models.IntegerField(default=0)),
                ('visibility_radius', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('boardSize', models.IntegerField(default=10)),
                ('finished', models.BooleanField(default=False)),
                ('max_players', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('lost', models.BooleanField(default=False)),
                ('inControl', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submarine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('strength', models.IntegerField(default=0)),
                ('experience', models.CharField(default=battleships.models.ship.Experience('RECRUIT'), max_length=7)),
                ('experience_points', models.IntegerField(default=0)),
                ('visibility_radius', models.IntegerField(default=0)),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.GamePlayer')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_battleships.submarine_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete='cascade', to='battleships.GamePlayer'),
        ),
        migrations.AddField(
            model_name='frigate',
            name='game_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.GamePlayer'),
        ),
        migrations.AddField(
            model_name='frigate',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_battleships.frigate_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='destroyer',
            name='game_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.GamePlayer'),
        ),
        migrations.AddField(
            model_name='destroyer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_battleships.destroyer_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='ship2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.Destroyer'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='ship3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.Frigate'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='ship4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.Submarine'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='game_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleships.GamePlayer'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_battleships.carrier_set+', to='contenttypes.ContentType'),
        ),
    ]
