# Generated by Django 2.1.3 on 2018-12-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0003_auto_20181202_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='ship',
            new_name='ship1',
        ),
    ]
