# Generated by Django 2.1.3 on 2018-12-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0007_auto_20181218_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='experience',
            field=models.CharField(choices=[('RECRUIT', 'RECRUIT'), ('SOLDIER', 'SOLDIER'), ('VETERAN', 'VETERAN')], default='RECRUIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='destroyer',
            name='experience',
            field=models.CharField(choices=[('RECRUIT', 'RECRUIT'), ('SOLDIER', 'SOLDIER'), ('VETERAN', 'VETERAN')], default='RECRUIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='frigate',
            name='experience',
            field=models.CharField(choices=[('RECRUIT', 'RECRUIT'), ('SOLDIER', 'SOLDIER'), ('VETERAN', 'VETERAN')], default='RECRUIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='boardSize',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='submarine',
            name='experience',
            field=models.CharField(choices=[('RECRUIT', 'RECRUIT'), ('SOLDIER', 'SOLDIER'), ('VETERAN', 'VETERAN')], default='RECRUIT', max_length=20),
        ),
    ]
