# Generated by Django 2.1.3 on 2019-01-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0009_gameplayer_game_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
