# Generated by Django 2.1.3 on 2019-01-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0011_auto_20190110_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete='cascade', to='battleships.GamePlayer'),
        ),
    ]
